# These values are read from the Teensy

Header header
uint32 millis
float32 speed_wheel
float32 brake_pressure_1
float32 brake_pressure_2
float32 brake_encoder
float32 steering_potentiometer
float32 steering_encoder
float32 temperature_oil
float32 temperature_water
float32 lambda
float32 gear
float32 distance_wheel
float32 distance_left
float32 distance_right
float32 distance_front
float32 energy_used
float32 magnetometer
float32 autopilot
float32 batteryVoltage
float32 engineBatteryVoltage
float32 emergencyButton
