#!/usr/bin/env python

import sys

from ecocar_gazebo_rqt.ecocar_sim_control import EcocarSimControl
from rqt_gui.main import Main

plugin = 'ecocar_gazebo_rqt'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))